name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install UI dependencies and build
      run: |
        cd ui && npm ci
        cd ..
        npm run build

    - name: Install vsce
      run: npm install -g vsce

    - name: Package extension
      run: vsce package

    - name: Get version
      id: version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Extract changelog
      id: changelog
      run: |
        # Extract changelog for current version
        VERSION=${{ steps.version.outputs.VERSION }}
        sed -n "/## \[$VERSION\]/,/## \[/p" CHANGELOG.md | sed '$d' > current_changelog.md
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        cat current_changelog.md >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.version.outputs.VERSION }}
        body: ${{ steps.changelog.outputs.CHANGELOG }}
        draft: false
        prerelease: false

    - name: Upload VSIX
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./k8s-translation-helper-${{ steps.version.outputs.VERSION }}.vsix
        asset_name: k8s-translation-helper-${{ steps.version.outputs.VERSION }}.vsix
        asset_content_type: application/zip