name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          ui/node_modules
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Install UI dependencies and build
      run: |
        cd ui
        if [ ! -f package-lock.json ]; then
          npm install
        else
          npm ci
        fi
        cd ..
        npm run build

    - name: Install vsce
      run: npm install -g vsce

    - name: Package extension
      run: vsce package

    - name: Get version
      id: version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Extract changelog
      id: changelog
      run: |
        # Extract changelog for current version
        VERSION=${{ steps.version.outputs.VERSION }}
        if grep -q "## \[$VERSION\]" CHANGELOG.md; then
          sed -n "/## \[$VERSION\]/,/## \[/p" CHANGELOG.md | sed '$d' > current_changelog.md
        else
          echo "## Release $VERSION" > current_changelog.md
          echo "See full changelog in CHANGELOG.md" >> current_changelog.md
        fi
        {
          echo "CHANGELOG<<EOF"
          cat current_changelog.md
          echo "EOF"
        } >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ steps.version.outputs.VERSION }}
        body: ${{ steps.changelog.outputs.CHANGELOG }}
        files: ./kubelingoassist-${{ steps.version.outputs.VERSION }}.vsix
        draft: false
        prerelease: false